name: Link check
on:
  push:
    branches: [ main ]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lychee link check
        uses: lycheeverse/lychee-action@v1
        with:
          args: --no-progress --verbose --exclude-mail --timeout 20s .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
